---
driver:
  name: vagrant
  driver_config:
    require_chef_omnibus: latest

provisioner:
  name: chef_zero
  solo_rb:
    ssl_verify_mode: verify_peer

platforms:
- name: debian-7.7.0-amd64
  driver_config:
    box: debian-7.7.0-amd64
    box_url: https://vagrantcloud.com/ffuenf/boxes/debian-7.7.0-amd64/versions/2/providers/virtualbox.box

- name: ubuntu-14.04.1-server-amd64
  driver_config:
    box: ubuntu-14.04.1-server-amd64
    box_url: https://vagrantcloud.com/ffuenf/boxes/ubuntu-14.04.1-server-amd64/versions/12/providers/virtualbox.box

suites:
- name: default
  run_list:
    - recipe[php::default]
    - recipe[php::ioncube]
    - recipe[php::oauth]
    - recipe[php::predis]
    - recipe[php::xdebug]
    - recipe[php::gnupg]
  attributes: {
    "dotdeb": {
      "php55": true
    }
  }
