---
driver:
  driver_config:
    require_chef_omnibus: latest

provisioner:
  name: chef_zero
  data_path: test/shared

platforms:
- name: debian-8.9.0-amd64
  driver_plugin: vagrant
  driver_config:
    box: ffuenf/debian-8.9.0-amd64
    box_url: https://atlas.hashicorp.com/ffuenf/debian-8.9.0-amd64
    box_check_update: true

- name: debian-9.1.0-amd64
  driver_plugin: vagrant
  driver_config:
    box: ffuenf/debian-9.1.0-amd64
    box_url: https://atlas.hashicorp.com/ffuenf/debian-9.1.0-amd64
    box_check_update: true

- name: ubuntu-14.04.4-server-amd64
  driver_plugin: vagrant
  driver_config:
    box: ffuenf/ubuntu-14.04.4-server-amd64
    box_url: https://atlas.hashicorp.com/ffuenf/ubuntu-14.04.4-server-amd64
    box_check_update: true

- name: ubuntu-16.04.3-server-amd64
  driver_plugin: vagrant
  driver_config:
    box: ffuenf/ubuntu-16.04.3-server-amd64
    box_url: https://atlas.hashicorp.com/ffuenf/ubuntu-16.04.3-server-amd64
    box_check_update: true

suites:
- name: default
  run_list:
    - recipe[php::default]
    - recipe[php::predis]
    - recipe[php::xdebug]
  attributes:
    dotdeb:
      php_version: '7.0'
    php:
      xdebug:
        enabled: 'true'
        cli:
          enabled: 'true'
    redisio:
      version: '4.0.2'
      checksum: 'b1a0915dbc91b979d06df1977fe594c3fa9b189f1f3d38743a2948c9f7634813'
      safe_install: false
