---
driver:
  private_networking: false
  ipv6: true

driver_config:
  digitalocean_access_token: <%= ENV['DIGITALOCEAN_ACCESS_TOKEN'] %>

provisioner:
  name: chef_zero
  data_path: test/shared
  require_chef_omnibus: latest

platforms:
- name: debian-7-0-x64
  driver_plugin: digitalocean
  driver_config:
    region: ams3
    size: 512mb
    ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEY_IDS'] %>

- name: ubuntu-14-04-x64
  driver_plugin: digitalocean
  driver_config:
    region: ams3
    size: 512mb
    ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEY_IDS'] %>

suites:
- name: default
  run_list:
    - recipe[php::default]
    - recipe[php::ioncube]
    - recipe[php::oauth]
    - recipe[php::predis]
    - recipe[php::xdebug]
    - recipe[php::gnupg]
  attributes:
    php:
      xdebug:
        cli:
          enabled: "true"
