---
driver:
  driver_config:
    require_chef_omnibus: latest

provisioner:
  name: chef_zero
  data_path: test/shared

platforms:
- name: debian-7.8.0-amd64
  driver_plugin: vagrant
  driver_config:
    box: debian-7.8.0-amd64
    box_url: https://atlas.hashicorp.com/ffuenf/boxes/debian-7.8.0-amd64/versions/1.0.5/providers/virtualbox.box
    box_check_update: true

- name: ubuntu-14.04.2-server-amd64
  driver_plugin: vagrant
  driver_config:
    box: ubuntu-14.04.2-server-amd64
    box_url: https://atlas.hashicorp.com/ffuenf/boxes/ubuntu-14.04.2-server-amd64/versions/1.0.5/providers/virtualbox.box
    box_check_update: true

- name: debian-7-0-x64
  driver_plugin: digitalocean
  private_networking: false
  ipv6: true
  driver_config:
    digitalocean_access_token: <%= ENV['DIGITALOCEAN_ACCESS_TOKEN'] %>
    region: ams3
    size: 512mb
    ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEY_IDS'] %>

- name: ubuntu-14-04-x64
  driver_plugin: digitalocean
  private_networking: false
  ipv6: true
  driver_config:
    digitalocean_access_token: <%= ENV['DIGITALOCEAN_ACCESS_TOKEN'] %>
    region: ams3
    size: 512mb
    ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEY_IDS'] %>

suites:
- name: default
  run_list:
    - recipe[php::default]
    - recipe[php::ioncube]
    - recipe[php::oauth]
    - recipe[php::predis]
    - recipe[php::xdebug]
    - recipe[php::gnupg]
  attributes:
    php:
      xdebug:
        cli:
          enabled: "true"
