---
driver:
  driver_config:
    require_chef_omnibus: latest

provisioner:
  name: chef_zero
  data_path: test/shared

platforms:
- name: debian-8.6.0-amd64
  driver_plugin: vagrant
  driver_config:
    box: ffuenf/debian-8.6.0-amd64
    box_url: https://atlas.hashicorp.com/ffuenf/debian-8.6.0-amd64
    box_check_update: true

- name: ubuntu-14.04.4-server-amd64
  driver_plugin: vagrant
  driver_config:
    box: ffuenf/ubuntu-14.04.4-server-amd64
    box_url: https://atlas.hashicorp.com/ffuenf/ubuntu-14.04.4-server-amd64
    box_check_update: true

- name: debian-8-0-x64
  driver_plugin: digitalocean
  private_networking: false
  ipv6: true
  driver_config:
    digitalocean_access_token: <%= ENV['DIGITALOCEAN_ACCESS_TOKEN'] %>
    region: ams3
    size: 512mb
    ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEY_IDS'] %>

- name: ubuntu-14-04-x64
  driver_plugin: digitalocean
  private_networking: false
  ipv6: true
  driver_config:
    digitalocean_access_token: <%= ENV['DIGITALOCEAN_ACCESS_TOKEN'] %>
    region: ams3
    size: 512mb
    ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEY_IDS'] %>

suites:
- name: default
  run_list:
    - recipe[php::default]
    - recipe[php::predis]
    - recipe[php::xdebug]
  attributes:
    dotdeb:
      php_version: '7.0'
    php:
      xdebug:
        enabled: 'true'
        cli:
          enabled: 'true'
    redisio:
      version: '3.2.5'
      checksum: '8509ceb1efd849d6b2346a72a8e926b5a4f6ed3cc7c3cd8d9f36b2e9ba085315'
      safe_install: false
