---
provisioner:
  name: chef_zero
  data_path: test/shared
  require_chef_omnibus: latest

platforms:
- name: debian-8-0-x64
  driver_plugin: digitalocean
  private_networking: false
  ipv6: true
  driver_config:
    region: ams3
    size: 512mb
    digitalocean_access_token: <%= ENV['DIGITALOCEAN_ACCESS_TOKEN'] %>
    ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEY_IDS'] %>

- name: ubuntu-14-04-x64
  driver_plugin: digitalocean
  private_networking: false
  ipv6: true
  driver_config:
    region: ams3
    size: 512mb
    digitalocean_access_token: <%= ENV['DIGITALOCEAN_ACCESS_TOKEN'] %>
    ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEY_IDS'] %>

suites:
- name: default
  run_list:
    - recipe[php::default]
    - recipe[php::predis]
    - recipe[php::xdebug]
  attributes:
    dotdeb:
      php_version: '7.0'
    php:
      xdebug:
        enabled: 'true'
        cli:
          enabled: 'true'
    redisio:
      version: '3.0.5'
      checksum: '4c176826eee909fbdc63db1c15adc22aab42d758043829e556f4331e6a5bd480'
      safe_install: false
