---
driver:
  driver_config:
    require_chef_omnibus: latest

provisioner:
  name: chef_zero
  data_path: test/shared

platforms:
- name: debian-7.9.0-amd64
  driver_plugin: vagrant
  driver_config:
    box: ffuenf/debian-7.9.0-amd64
    box_url: https://atlas.hashicorp.com/ffuenf/debian-7.9.0-amd64
    box_check_update: true

- name: ubuntu-14.04.3-server-amd64
  driver_plugin: vagrant
  driver_config:
    box: ffuenf/ubuntu-14.04.3-server-amd64
    box_url: https://atlas.hashicorp.com/ffuenf/ubuntu-14.04.3-server-amd64
    box_check_update: true

- name: debian-7-0-x64
  driver_plugin: digitalocean
  private_networking: false
  ipv6: true
  driver_config:
    digitalocean_access_token: <%= ENV['DIGITALOCEAN_ACCESS_TOKEN'] %>
    region: ams3
    size: 512mb
    ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEY_IDS'] %>

- name: ubuntu-14-04-x64
  driver_plugin: digitalocean
  private_networking: false
  ipv6: true
  driver_config:
    digitalocean_access_token: <%= ENV['DIGITALOCEAN_ACCESS_TOKEN'] %>
    region: ams3
    size: 512mb
    ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEY_IDS'] %>

suites:
- name: default
  run_list:
    - recipe[php::default]
    - recipe[php::oauth]
    - recipe[php::predis]
    - recipe[php::xdebug]
    - recipe[php::gnupg]
  attributes:
    php:
      xdebug:
        cli:
          enabled: "true"
    redisio:
      version: '3.0.6'
      checksum: '6f1e1523194558480c3782d84d88c2decf08a8e4b930c56d4df038e565b75624'
      safe_install: false
