---
driver:
  driver_config:
    require_chef_omnibus: latest

provisioner:
  name: chef_zero
  data_path: test/shared

platforms:
- name: debian-9.3.0-amd64
  driver_plugin: vagrant
  driver_config:
    box: ffuenf/debian-9.3.0-amd64
    box_url: https://app.vagrantup.com/ffuenf/boxes/debian-9.3.0-amd64
    box_check_update: true

- name: ubuntu-16.04.3-server-amd64
  driver_plugin: vagrant
  driver_config:
    box: ffuenf/ubuntu-16.04.3-server-amd64
    box_url: https://app.vagrantup.com/ffuenf/boxes/ubuntu-16.04.3-server-amd64
    box_check_update: true

suites:
- name: default
  run_list:
    - recipe[php::default]
    - recipe[php::predis]
    - recipe[php::xdebug]
  attributes:
    dotdeb:
      php_version: '7.2'
    php:
      xdebug:
        enabled: 'true'
        cli:
          enabled: 'true'
    redisio:
      version: '4.0.8'
      checksum: 'ff0c38b8c156319249fec61e5018cf5b5fe63a65b61690bec798f4c998c232ad'
      safe_install: false
