AllCops:
  Exclude:
    - 'berks-cookbooks/**/*'
    - 'Guardfile'
    - 'Gemfile'
    - 'Vagrantfile'

AlignParameters:
  Enabled: false

Encoding:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

RescueModifier:
  Enabled: false

AbcSize:
  Enabled: false

RegexpLiteral:
  Enabled: false