AllCops:
  Exclude:
    - 'berks-cookbooks/**/*'
    - 'Guardfile'
    - 'Gemfile'
    - 'Vagrantfile'

AlignParameters:
  Enabled: false

Encoding:
  Enabled: false

Metrics/LineLength:
  Enabled: false
  Max: 100

Metrics/MethodLength:
  CountComments: false
  Max: 100

RescueModifier:
  Enabled: false

AbcSize:
  Enabled: false

RegexpLiteral:
  Enabled: false