language: ruby
sudo: false
bundler_args: --without kitchen_vagrant --without development
rvm:
- 2.2.0
before_install:
- echo -n $DO_KEY_CHUNK_{0..30} >> ~/.ssh/id_do.base64
- cat ~/.ssh/id_do.base64 | tr -d ' ' | base64 --decode > ~/.ssh/id_do.pem
script:
- bundle exec rubocop
- bundle exec foodcritic -f any .
env:
  global:
