language: ruby
sudo: false
bundler_args: "--without kitchen_vagrant --without development"
rvm:
- 2.4.0
script:
- bundle exec rubocop
- bundle exec foodcritic -f any .
notifications:
  slack:
    secure: Ort9Jxk2Hdau/3CpVQfRY2s8RQ1fduQ+8mK+pKk0aVVCCQojjk7+WdgjvskJEoKEWKi5ES9E+9YosBAcnyYyVHG+pDRkeiODrgKYq5bgKLnoehEpSQmNJpGHKxHgPvX9hJOaElHI4rfWo4zStGH1G28+GIogSrICWpztW5sMKk0=
