language: ruby
sudo: false
bundler_args: "--without kitchen_vagrant --without development"
rvm:
- 2.2.1
before_install:
- echo -n $DO_KEY_CHUNK_{0..30} >> ~/.ssh/id_do.base64
- cat ~/.ssh/id_do.base64 | tr -d ' ' | base64 --decode > ~/.ssh/travis_id_do
script:
- bundle exec rubocop
- bundle exec foodcritic -f any .
- bundle exec kitchen test $KITCHEN_INSTANCE
after_script:
- bundle exec kitchen destroy
env:
  global:
  - KITCHEN_YAML=.kitchen.cloud.yml
  - secure: K2ApMgKN1ZrF3jSlsSG08/cj72L2BjpSBWJgA9BfjytIMJxWQPKWkLjnCGj/lS4WoBt1qC8KQJBxYm3gUh6OQ8SrPm+A6IHFuOIdYJMwDYXiS3jKVta+B6BE4MSnNplc4YbJXESoTV8SYaJxNlHDyit9smsSPbhwy/r1kaTniIk=
  - secure: H4dXZyf/PYGZh7ygFEZMyqg66a03S95ZvGFWwCyWrfVV30H/Uu+WHaipqRBZ3Oopc33wWMDL+wFexxafHzNyz/9jCE2dpbgp2wepM4h2hySyzwuf/HrilXrWCk6PpwN36KI+GD7rddvW/zgTScPOQIAz6GfQIfqXozGpc9a2uEc=
  - secure: PRV3McRotpW1brOrixwWLThlgoVF63aXhBNzG+9fTzA4uP0R+akFQo7wA0npyTiLI9YptUP9l2CBawUmYrj1iJ06niNzLqFJIRJem7SXbHJscv1QgPfUmKr2ee/I2boTv2fPfxo9G/B4WYOwSE4SOQ5k/zK2N3Lz+RRmSWOsWBw=
  - secure: hT1JV0DztZg9M9pbB8veXN3wA09JdDfJwvHNB1ZweUt11sEAO6WyEKwJMC88cTvP7J2shR3kYhnFt1Bo+2qbH7koOvVDxC2ABaewJE++M1jfpHdH9xOfBYQc/p1JZIs7mFs9wRlSxRBYV0bt1rgJwgKZDlnqb0TN3CtPwiH0eUU=
  - secure: J5SZXguaCZV/PQOmoePp4vAAJxHiIAo00Hi8CEDZW5DfYR0QTXvbAj87hsrNEWH9PZy8sylaDjC0Fw0DNsta+xBCmGtRiyaci1weB2xzKWy9dfXs0ITgPS/WnRZCYu9sebgT3Ty0N9FBe7CJeINvhhAcdOWXS68Ti3B+TNoq8E4=
  - secure: ipEORA8NvjnkVshpeKcxy5urSpwfh8iZ/+B7Z7vpeOAFTyHafpzphQ7SRtoJ4Y+NsdIUnev+uPyqr3VY8KQMWfCwIlQ6/PBguTcsOC3WbSbQcYzlzbY7NOZZuXHr5f4eQr+XM1c9nA8XAD+aI6CFvaR1py7VkL2fvLWz4v2LS9E=
  - secure: cVumrfZomcTqD5uv1UA87kc2OHhB88mmSNKEooN3fTjObrdpX1dQMaJivaHwoqmHtYI305sR8ohmv8vScb4pgMCCnN+9BAZR3isD7Q7i97+9fkxBCqFfY4Z7Zs3n8+0GJca+/uemKT+H2dbKILAaSj0LzmsX++7tJT6f+NIoVWU=
  - secure: HG2OymMA+4JSUycTUDl8GmRxF6MKGtl6ZTw/6tbcozGaiFS9MlEO9DTL7lEsto0rpmUB8obeFDLqWJvAB+8hkNHwMARhgZXNUf2j0KU6rtOo6YiYYl7CDCPAEmodPjUmvtSKGDDv0X0SOShT9td7RmEWLzXX+udZTWNsARp1DxE=
  - secure: JKhqS6QT720tbV/rqibtSPbrvGfdznw7Q0vkoCkJHVKL8S8CuP/1cKgJd2Y/m6WhUyEp4JkaZqMlW73cuS0cwjk/ylSsb9vDJaxxod7SbXK11woRjIUY5rV5U9OEg6p8faEa3Bw8cm3ovRY2ZcSTegv+f/x1HmcNZx6a6d+NhdQ=
  - secure: GTXorCuQfi9RTTv+JOppFBgVTglipB5tCc/JNlXo28h0KS+Dcy84oGYO0vfJY+JPH3NuIU5ks+Wubr/Mi0K/uyc7NSu/6mhmwM38rv0gczxHg5yt2rrhrqrV5/eaoffVuWfh4c1h7cAMOQRymqN3oIETOZGq2C+0gmpVcuDe8zE=
  - secure: HF5KJPxcXtLmGOd/1rJzHSDt/svQh/dI+QK9L4+/EjfWt8/f8On+XCacgMQS2xn6GWyJa81v+mbIo7Ac4aRmacGFV7h36wVjugfTUih4DjZk7U/uYPMnpEhMoXcbigSqA7NF2x93YdIw4WDueNodxgRAuaWp32yLbq5j+HgS5Vs=
  - secure: F4XGl3fA1kzU3s7GuureKtgdGf57QtF4ZkL9gg1M9r2uWI4A4K8dlsOT98yvJfJLXMzPWMuxB0gV7JIRR20xZ/nNe1esk+d5CLcW+dUrE833MOoXiJ00kkTm6/NLNvKsvHaaxMDIIzQf0Lg5MbgmelSDfbjxun6aOrAgPDLa+3w=
  - secure: kE2duja8aYCWJpbTZyMCTDDNeEi7CrJQjSbXgH1HK77v0Jiw6DLCMel22xo725xcW6WsmqYk3oCo88vNrAy0jAhKcQtOgrP6yR0061/e5a/OS8BkQvJfD7yr3GRFJXd3bGMH43uKzpjj58Gz5dJZeUkbQTKgpYaBdgMyWz1cSRc=
  - secure: HEh+bhSaejUml/Qskc2MCk/1yzlP2JdT1HBM6RB5NlXZ+7eKs1ilSMZ/zp/Gncw2AJ2/OymJ9392FhvALf5vKY9W8mplu/oaBtG3scrRXidy0il4nMOwF7oBjCLqRA4n6d6dNsBlmHqp/I7707YTQ8UaxpHiJ2gxFi4Tcp7lI6g=
  - secure: Yx+z94HvoQTpqYECugYjwA3a4CcGoekfbabwufxN7JDn2fNkJpMpHQaoEhminFs1qwY1TpKLVzZRpQdmi8SGEfjSXzGOaE7lI6RmjUwsufcE0eVrtqQXmL54i53dtO9BboMbju/KTU+i72ooBqaCX2oI7HT/NxEM4l6Mec20l1U=
  - secure: OWSBMbs2adhBzyH9kdcaQQ3IFcIUoWTB0gFlaL5nyt1kA3d/L0zfAKzqWnzw0BG4yuUPMc+x5/EwfYVyPqV9iG4LbfilJc9SzdWnUewZV/DYQ17Kub/lrVnomhC+S1zVm1B3TPB+uFXGZocIF49z3MDvpCvaQW5achbwafeipnA=
  - secure: hUfuPpixwRPkceC9W5DAO5M7+qdB2pe1mZx22efEapyeH+iI1NRMPPFLwRnx+lpdeY0Es0NutI/5X9dactf5krLJNyRthQLJ6I9ZaICHOPjT88ABFUAXqgLxjFpnQw+ZSsFy2gdpIlOmR3hPhqZ7PLzK/fDjRG66JPGUtU0DYvk=
  - secure: L3GufRjsHI3bUMMpQ2+Ilnzvp7PhXsh4b8/rcbvcP8iTjko76Vz7s5hD5BQXsMFFndLmO7KYDIHp5ZrQlkZ6jZeBsuKdefUiPZGuJZlDc8scpW8XHLEHWN+5FIC3V8Aiu+H0NzxjjiOrt5qe4ozP5FaDe8ad9yLD/mX2Sf5C5hg=
  - secure: h/A/YsETohE80x497V4gUMKPsD8In7KgvfcM73w2zub4PQXzbhA1bvdxvPbL0G6emzYGfGyd+uqURSR4Wz/i8VAHUiKd/QcHdHmiU0kthQMEkG61JaKqjwaqSwnVKtdF5vcplXOAJTTy7TGPYIVOIaRAVfhFZo0E4AyBKA1fkQA=
  - secure: UQEl+RPMK+pDrcHBVFuz6kkKKvNEflkeNnpFk7zH3voT5sarzEn9SYXEW/rFhwNQhJb/3y+DmuY7KIzJa+Rq3/xjrQwsOkKwtRqTNCW2AiRBUy1+qDOUwdXSbTTFsEfHfCtxnTqvH4YE5SxY7+tDbg3MHr9kWQJG/2g1Svw/+YU=
  - secure: Ou6b0uRRlvWk8nZt3rpEYtGWxPKeQPvgxiOfUPUCfN4hAgEX73x6jjEtP4JryPRRqYQWBB8BMp2p2UFAKpTzICM1BhTrnFjeyf4jkFeojavjBSQ6qmNJCl/qwEI38uBOXgg4apAupe+CJgqxrxNiZaPclSkL9O002wsIfuOqLjM=
  - secure: a/sVB5SOChjUCfx8U/A19gBOJHYZKu2L7ita5NTyhF79ciVVuYgosO+MzlHf+Pkg5GndncLUYfcTqMJfFrDaR7gq/UiElEzHS+jaP7sYUsdf/64xMITcuN9Zsq8ZH787miWtPGt4m4q18qCJ9D3VsB5CEpJt3YlEcnOfAQRn2v0=
  - secure: JV5OjJBf5dVhamukjIEWYrbsRKngmyp2CC0YfBFGoOcdMqycd3fpfxZEFMvWivmiewawizZLFtx0NYok14YxcZSrH9U2K86rly3go9Izt6QwBUq/FUxRnGutp03WARRvdiQGsOqBXLu094Vm+o6PRxKfOQqWHAAAiCFuCXXSMNE=
  - secure: Di6aE+W+SXgO/AhvXQYvlfDLWnq1zkJqVbyRG8shrkxkVaTbq4U75mrZpj32GxvRlphI+3u9L3TaHSK9IdEaWt/Y7478AlPL53v6OpNF4fwkU7KIkkvUESDmhDNhUeKe3tqCH0T4yEmlO3qIPNu5p22DNZZR7qBF5mWeL0VB5K0=
  - secure: eKCPfdDsKDERifY/m/eIDif9Pm3KtI+1f5uAbCHnwqxaq+UipB6bZd668H05bdbS7sbrTosAQX+yt5HQSW+s7UCFo+TrpgPXUA/Gj5cKB/GKwyf15a8yZaFQGW1xgvr4zKlGFRAxqpISGZHf4LNqyal5SXT7kc8RtsWSC0h7QEs=
  - secure: hyNgPPltmRIpVpj/EOIZ3v2FKOVBX0aWTt9huILNihpvRy0W0Wjk0rq3dGrcOeFV96yX5SHO4fkuWhIOrrmnnSU0SjAF/a0DaYStN4ohdrOPUbh26WriBdUi/vIyrv/ji3pZl//uAlNQCgPxQPUTq6ERY6wlyF0bSbTNbd/2GbI=
  - secure: A2C/rUF2Zf3K9jWximFO5zBsbFZieTRLQdfuyNjU/QTniPidndljedrl53M78AOA6BnHcdRSEhwv/cSsrOuNXovwIf++48TVbS0VCVMG2+XL5gXUeSJ9pVGntEpCe6nhENuD8sQgrEnGWF9gwPjAhAR0rcOVwtIIfqXNFyBT2Pg=
  - secure: PAhNuaM/IozI1laURHVdhrIDhoi9RMWTNcTCa/pytOn+IVUf2swD8dWmO952d1+sC/s8L0AP+9QunvI8JVCayZRWd3oC4hqsopRiQUs1GaBgFBB7IonpGPc8htWzH1M/KBD9rfi2Hu04ma1uqljvehNXkI/jJx9NoLmZkzlR1rw=
  - secure: PkSLKkxGzBQXLUBBvEBbxleeIyKZIi2GSl0K1J1PDirVSQckU65138LCaNjMTg7C4sF+M63JIjkd43c/7/4418DE0OgVoXO3xzhBVFQR/RzoOc1CYSSp/L2wQg3o3Xdq55edJpI3YHIOattV0G5SKfxj/srelHXu1tMBRxJipTI=
  - secure: VkGnACPI8we74F438Nt9p3ES9niSjVC1orWTJSUlvydqB2lD7+73w8JDaJxJ22hSxBIZ6SbNgpMO03towcI7iiKuEv2SbSk+o8EgoxJLbnyslGmE299sA4ujHAcK2g6efMXxXK8a1262miEOacfpGGx5bVQuwO5Sku49VR9JoTM=
  - secure: a6HSgK5MiMr4E6qBQpIqUlIgZ/nrIR/fRz7EU9wmtwcOoAonh9AFROAxHmiBM3BDIjWlQtk5V6Q0HJQSwygayobly+cI95WdYgWH8GQ0t68US40iScqByNivE/rsDiGL2Qwp74BSo8kqr27FNo484Mftsft0PXYB+cYvZylVoTM=
  - secure: PltfZDAjfQetxRAj13YwnzElaloHoQUCZNXSNhBR3CoIrDz6sxJ0DvDO1Wi+jgm8sMFZ5NwLcxGIJ60Asd1VfplsE1fGsroz2ocdflZdqWfew0arpX2frfMprLivK8cVOcBHxdUQH3SjkesvtfFMWca43a/U8Fs+k+JcDGmmCus=
  matrix:
  - KITCHEN_INSTANCE='default-debian-7-0-x64'
  - KITCHEN_INSTANCE='default-ubuntu-14-04-x64'
notifications:
  slack:
    secure: Ort9Jxk2Hdau/3CpVQfRY2s8RQ1fduQ+8mK+pKk0aVVCCQojjk7+WdgjvskJEoKEWKi5ES9E+9YosBAcnyYyVHG+pDRkeiODrgKYq5bgKLnoehEpSQmNJpGHKxHgPvX9hJOaElHI4rfWo4zStGH1G28+GIogSrICWpztW5sMKk0=
