language: ruby
sudo: false
bundler_args: "--without kitchen_vagrant --without development"
rvm:
- 2.2.1
before_install:
- echo -n $DO_KEY_CHUNK_{0..30} >> ~/.ssh/id_do.base64
- cat ~/.ssh/id_do.base64 | tr -d ' ' | base64 --decode > ~/.ssh/id_do
script:
- bundle exec rubocop
- bundle exec foodcritic -f any .
- bundle exec kitchen test $KITCHEN_INSTANCE
after_script:
- bundle exec kitchen destroy
env:
  global:
  - KITCHEN_YAML=.kitchen.cloud.yml
  - secure: b5qI7HsyWuVGgqTYHdSykdzU8bLR/0U5FRUrSdKwj3hgrCRm7w73mndLtDjqHfNPM7FyhNIGWXIvG+w52wyZmL0FwBBATVEf0cnYxK6wM5P3y7g7X/YUS24cDgB5j8ERKskUtMxUz/WUzn3iGJwsZFuNCAqZRf6ScoxHgm9O77Y=
  - secure: G0HtE4q+7nJObnPhq4hzcQTv0kk7nG+0ch8LnBtrhpoWyAOpV0S7copZQ+al4x29TyUojYyje+fwqXFdrfhK5XrbUqKCF6VShxl+u4k+lSokZSREXuE7SCxNTyeN1FYrjuAjopdVcQyL22SQKF1lu+qTB+Cbqjecv0HbPX26yZ8=
  - secure: H2gRl0CLtuskdKSCu/9fqGhgaUuPyafXzpdOYsPk2SmxGRZY2IWEawA4DKuCvIfWtdI8rtLNvvLRTn90tkyyLoQsWutZeYJyLB6PJ892piJdHeCO6oGtBwjMlh0O1EnS+3mGWWWnq9GDw0afRm7zlBIGjHnkTi/DRWa+wueEh08=
  - secure: PGSpTfW5aDFung2oeksPwZPFboqX7FBIvmuPyNC8MC5AbKUts02z8XxvgSeq7hpHEXuQ9KPx+OOBsCw8mGbdUmCzUesHgawrQKF8oFrzVRsiFSCPe/YdUZfeJvaajN+cwR4Cbhth0qBjmWD4NszEjELqDmpg9qtExwMGP6A5ttc=
  - secure: dDLiBLyKynivxY0gFoyjf7X1NBWV//xUJqQSVLdN4Hgj4xQK/9f3NRVobak1rcwHS5wlCNm8K+SRnu8xB85ttOZ3N7R0XUOv+7yy8+eC4q25zkfUqYdQHZC7FO2dKn9H/kMMtOUOM+9nJlx4UJ5PMphvvOEjClRE6jHeWR7fFZM=
  - secure: dvKXRjF5s1Hvr7cD/UeXWOKjESsAyGsPQSQWzwCf70p54/E/6UHoiiR0HVFeYfHHy29wu00Q7PsgBJky8e97zdFk4Gq+Zp34FLYgOx2hi5yNi/W0UyUVndah7Wo7RPl9etI636SyLUoDdSXST4dm8xRNyxiBjNPSBcRilsGf+oU=
  - secure: WSVeamML+Fpw4dFK+Q1cDDILi9Ctvb7YbiX+4Ohoq+G1zjy2xe0uEq5EP51O9MozndftNnAIX88HdO00rXZ9bCoImqJxV5YSLZhnJjv3jYBDha4nuCFdYvBdQaVgNZ6oOfLeSXLXv/EA+881E7DHwgBFjBX0Fj28eypGsC7XAD0=
  - secure: dfa9IMlLjVvZ9uN2GZq2fm7Xh0OUPx/rxz0aKZ2usAianyPut+F/mfQ/erm/DLOrridk4mBLrYAHHQ37LAtoj98bViWl1xhtfmm6BzrGebF1lMHl0tZ6VKO6cBN4mu+UeFkQ19Hr6Cc3FaZRA333Vj6TpTF2Ty1hxxoRQla7I1k=
  - secure: h8ClafPcsGF3SByrTLd3MV3yczKhcd0U11zRcobUVHqlgCpTAAujz/PWtAUjSVby5GdmbV4y2+nBYu+9r/xS3sRcBDgNnpbxy2oFZ7txuYUE86lpqxo8vpzxzD5cPYBQcV220ZUhBUAFmWDnLePbB11S7n6yUVv6/ykDO3KPd68=
  - secure: dLWHpwA5BvkKm3xrOpEaeBjma1jExZkCkWmIsrLvUYLUXlxZRlvutDn4rKAUzEJipx/KyjnOPJA7cwi5yyLm4FzjASPPzMdXx0EStkGPaBox2MLIyI3Ecp4AKWr0c0Cee9S8d7Jbr9mRH4ryzIl8G90MKnPUqDGxg6ta32JLDYM=
  - secure: OUzfiSZveCCdG49FlG8ITUaVfe+eUUrDeIfVgG12a08CCvxTfiVvCAMdenxDFkGOuVXaiTzt5T9otuI5fXZbLWP2d3Sz8b4zFosg7G8/Hv3wAs6kJH73mY/a1TwJ3IVr3+e+XEKxvOg7+gtDTvFLJ/G9oiZbxQwZWu3wXjdGo2c=
  - secure: UukqsXlQjVt7OfCr+sK66wwzyfFTol/GjNv9kp/Rjw7ztS2iK7BOqzVN101U38Pi63Wqu4dpKz1poSlvTUYrgCi5MXsLeY0Jgvm8EQyMhjbdXuasbGaq5yBzHMCOA4wp8YJFkyB3T6ln04X3XU0qSb7/y3w+QNdVE87gxe1KnS8=
  - secure: P4/xTOLeIbxJwvn5qej6+sQKmbqMNuP2qoBCW6KHAHyo9QavhpQM/hzvdK31Zly00ijU2H+UgevcrpKLsPCzSXKUAE+bXf836pe9u5Q0LC4m9RzkWyIpKjBnPeXAB6axWVBvKS25YGj+qmN0kA+QlTbuXM4SL66wMYb6CC5oYJ4=
  - secure: ME8wRee2YwMDlAEaQSA2o+MA/KLn9XRQJQ0NL+652Rdxe9RH7RBXPNcNM6oNBKcQjRjG8Hq9wHP0YDtxyMMfy0HgAF+ZIa/3fh8RbtgWjXCViC+qSD1ji35a2BNpL0WI7v8mefTkxZ/EKKub0QGakw9SS84Qioz4WLV/xQFnLGQ=
  - secure: dqZg4iuxQyGIyzmoS3yOQF6iSkWUtZc+mG+ms/pJSj82M9YjxIeTMv9NQFqzPKX8AstdB5c+K36HKhFvpkxftb0cn5dQJ/a4v8/xCiwX7hq7FGAlevvsO/tfNc72m4FdJZtqHsUMJPyCnChieSXvEyUDuBJh8T0Hwufk5Z7puv0=
  - secure: Vr905zSFct6FcKzveC/1i5LanggUWdFreaiqNBXJLai59M3mjIfBPygwUhVfqgEQQuGZh8hXK5FEE3BhgG4NZKrWmqnkY75N/GSxcHW0USYvUMDRiF3AU6b9lOWpqFqm/r1cnUKht5iKz81b5xeafVOMgmu/eIHHTKBfv7a1b54=
  - secure: CC74ijGPqVDQX/Q8rUMhuVuXy6NcNPl5g/z+lFU9OcNFJndP88pnw56x2vFjX57CGPgCvm5oRtUXPN+xm4nyh77xOJRjuwzYko0uRCjQI3smppFRFOWMz848bFbjbWhZ3Jk+nTID+W6zpoDaclAWMNb7i+oPqKfu/6U16Ka1TUI=
  - secure: EIEOxZI+CGOdwtq32BSA2kSFdgjZ1zXxLyEKI112DzLeCV8aYguBwyrGDX4eNz9IqSg7Eoopm/nu5DcZlpIPWkKgt82xcubCb7ZnARgIfMvl2fUmkTovdyflPL2P0lMg7SjfZpN8RYv010VGAzTpFGvBiZDBhBZ87e52vpvnpLs=
  - secure: UjUFJTbmkJoJXjuckKEDC/+uzdc48uSS8TzKy7wmAV1IQnCsmuZEZfrEnbO89J+R8rLe5wKHFtdFhcA8QfhvbIZon8vmRn4zrYqMDALw6Z68XfION2OJz0CF4/NPbMLyKNDCqrOmAVWq1oQhDGJyXcGfP4jCHlkb7YUD5e44SI8=
  - secure: AlcwRIrz9TD4O4tSYyVLIlpgidA52zOG1utYLtPfzuzyvc58XMMZ7I7xvWCInocIsgR9zOmUzJk6lr7ucCvk2v8u4C/E5mkPkR37P2m8uYAgwS2IDUFjra7sMSfT4LKs2rdDj0jye/1S4RnztoyEciwsLROut2t/hL4uHHYiBd0=
  - secure: f2WVkTHJ5a9VtzihOiFnet4Hl8ykPwFeejiL6Mcr5dKmacepXtU4LaAaMb3AmRUygYL4ddiiVxAz4Kk90uY4Z0TUpU6mA9UB5VBXnwnz/kmHNGl6TMzgmjTXpo70cYE95TwRvBf5GbU2Ayubt5Z0PxhZMzpfCbrgsJqGLjXyU5U=
  - secure: OZj7Pz40t1zu0GuO8WFJnVS3i+6a6EHSwlOi1cPUm+foOL4QzRLVLlcWUVrArmiNyTiHJ2VvP90IA/rx8UTGaTU4pIgFore3LebIJOkSZ2B5Sg4u8JxHS4jC2bKXnjb/SA4bgTymmK9NWDW1r8C00RAMbyxTSnSfxVJr5OacW94=
  - secure: IzmYkQo/Wmpldbo4d2x0hn1TPAohkFpooAClGx/e7kyWHUVW3jrEkQnmGhFJfVDM/waM7O0O0BCJyO1wJaReHBY44vrUdGF3TJg3qzZavMspFXB1SSSNLjJe71mcyuuJpCgJ89pIkLUiQ60/xR7gkZNV3x64avvD91jtKuI043A=
  - secure: GtpA+p8XKd4kgWQpKTt/iXG3uDPFqwDc2YjdHb35bPsiK63SPJtOqTadLLu2z/SDs/Slbr/CkjdkVDuXLdRSskItPgZX6hoN35ZpRPZeXSvl8zs1ipbpiLd6wt8WYkYpHNwe4zPrlePO+g2aLemTbCRXNMazNu1fV9IpFnQ5EP4=
  - secure: P/EpjNr+sdDrHrC9PCFcAw25CtE7Gtlk3CgOwsLmxMr3PDYvHrpN6zvS+tmvKKBqM7OSG3Yu2kcjoLTu/1py2TiZE5ExndCPNYbhSwhCuJGmz4DXzUAZbET2quQCLTNZ7XrmvqjbB8cWaTfQbQbaw4STnm9YaS1CSK4DcnHEYIk=
  - secure: LiG9no3NeCWRPYwbsTBRukGEnxBfG0r8rGd2wuiDE+C3g5Gh3EdaVC1rDPs4C6Da/sQ/GV8vEhEN6OV9vsgMiRONSUBsKsGj2DFUw6aMbOtPSiRRJxU+6lAmToxSau6x1Gltu9LuarmQdT3nOcLk7gVA9noHTAD5dAxZZ90/v4w=
  - secure: Hy4mSlwm0boAdz2b9+fcr71qY6OqyEQH80N9In2frTw7ZZ5rZqQTD8pKRLlaxBYm92lScn3jdl7gNiHEUfSnDwqnOY1yEhi74wJE6Ajp/I97PQ+TJ5tcjhqtagU/VQGjUhexvNXiKoKaOKpQ5EGV26e24dmVRRyQgJHRkg5bryw=
  - secure: DUwRFwFNufgQA1Ocd7YUQ54/W7dLKbKQ9RAuKOVXIMgsaEF/ICDW5EWv5/nJYBso8zvPd8JVNGHH1b6rfznUv6AWbLO/DEgTYuzaoyvPa3ZA3h3vDT2xdpCw0PYvkq7g6oFUMa/XCA7bhzipV2XzN6FwvKQMKU5BMO5czAe2foc=
  - secure: dQHw9e0zdGKUoQ476MuK6RH/yXBpJcOsgTaHRYTgtSTuTByNsVTPuMiv1KWoFQeNKQzx0arRhYoowJv93vqVy6u844K0VObeMKzqlRPfA4HXGMmvohpWlXFupeD+qGYsut62AQLN8rr2sRlONQ2049aNlRQ0M/QZMgzO4dnpSDA=
  - secure: hX+5dj126ZF8Aj/mZZ3j4zwYOZV8+eiklzf6Fju19VDpwN59UMNop4wGUBatlLwXy4kMD5eFpD5yPxxWTqOM0NixmMZVqJi39pwlg/wCSclWY/CJwVxAB6Nfr9eMQoM3SvSm7Y96pFGEMm6eGlXNuZEP/aDDVBZzlzUKeA42qq8=
  - secure: G1Tec00RBplF3kcgPStbLz9u2LniwQqnpaBCp4654sSRRWJj59HcmRNaCEvSjyIrVVVBb2/ICVuDZxnUoUksB1alvpaSmZvXv9e6W06qtpC4fi4q9CIXOlnhkn9hZ2cLZ2cq3DqfSXNe/28+PRyklF+v4TpBNL89cdzOlB4t1BQ=
  - secure: f6tMXBMyF3KEUIwk/Mw8EzRRTxI3E/Pig+K3/Gi0goyH4XsUk8gIldO4KUQZzEz1APiBZEznv3wGM+99lnr14Qr2VNzDvAxgjs/xdGZb2UtUUzJr462zMeSokJnDEMMYU83Gkf8Ac89HNynjtYyV9a1DC991742CGYiHXG4S19Y=
  matrix:
  - KITCHEN_INSTANCE='default-debian-7-0-x64'
  - KITCHEN_INSTANCE='default-ubuntu-14-04-x64'
notifications:
  slack:
    secure: Ort9Jxk2Hdau/3CpVQfRY2s8RQ1fduQ+8mK+pKk0aVVCCQojjk7+WdgjvskJEoKEWKi5ES9E+9YosBAcnyYyVHG+pDRkeiODrgKYq5bgKLnoehEpSQmNJpGHKxHgPvX9hJOaElHI4rfWo4zStGH1G28+GIogSrICWpztW5sMKk0=
